In [166]:
using Pkg,LinearAlgebra, SparseArrays, Random,Distributions;

In [167]:
y=[1,2,3]
function get_Y(y)
    m=length(y)#number of rows
    n=m*(m-1) #number of columns
    res = zeros(m,n) #set the result
    start = 1
    for i=1:length(y)
        row = copy(y)
        row = deleteat!(row, i)
        res[i,start:start+m-2]=row
        start = start+m-1
    end
    return res
end
get_Y(y)

3×6 Array{Float64,2}:
 2.0  3.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  2.0

In [6]:
#fake data
y1=[1,2,3]
y2=[4,5,6]
Y1=get_Y(y1)
Y2=get_Y(y2)
Y=[Y1,Y2]
R=[1 0 0;0 2 0; 0 0 3]
w1=[6,7,8]
w2=[6,3,4]
W=[w1,w2]
t_square = 3
lambda0 = 4
get_Y(y1)

3×6 Array{Float64,2}:
 2.0  3.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  2.0

In [930]:
function get_para(Y,R,t_square,lambda0)
    m = size(Y[1])[1]#number of rows
    n=m*(m-1) #number of columns
    first = zeros(n,n)
    second=zeros(n,1)
    for i=1:length(Y)
        first += Y[i]'*inv(R)*Y[i]
        second += Y[i]'*inv(R)*W[i]
    end
    first += Diagonal(repeat([t_square],n))
    second += repeat([lambda0*t_square],n)
    mu = vec(inv(first)*second)
    return mu,Symmetric(inv(first))
end


#MCMC
mu,var = get_para(Y,R,t_square,lambda0)
rand(MvNormal(mu,Symmetric(var)))

6-element Array{Float64,1}:
 0.17152948528014167
 1.236810971570697  
 1.3317313024875497 
 0.49550384033609074
 1.6642142275827143 
 1.1425941486244353 

### Our case

In [7]:
y = [1,2,3]
function get_my_Y(y)
    m=length(y)#number of rows
    n::Int64=(m*(m-1))/2 #number of columns
    res = zeros(m,n) #set the result
    start = 1
    for i = 1:length(y)-1
        row = y[2:i+1]
        res[i+1,start:start + i - 1] = row
        start = start + i
    end
    return res
end
get_my_Y(y)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 2.0  0.0  0.0
 0.0  2.0  3.0

In [8]:
#Fake data
y1=[1,2,3]
y2=[4,5,6]
Y1=get_my_Y(y1)
Y2=get_my_Y(y2)
Y=[Y1,Y2]
R=[1 0 0;0 2 0; 0 0 3]
w1=[6,7,8]
w2=[6,3,4]
W=[w1,w2]
t_square = 3
lambda0 = 4

4

In [9]:
function get_para(Y,R,t_square,lambda0,W)
    m = size(Y[1])[1]#number of rows
    n::Int64=(m*(m-1))/2 #number of columns
    first = zeros(n,n)
    second=zeros(n,1)
    for i=1:length(Y)
        first += Y[i]'*inv(R)*Y[i]
        second += Y[i]'*inv(R)*W[i]
    end
    first += Diagonal(repeat([t_square],n))
    second += repeat([lambda0*t_square],n)    
    mu = vec(inv(first)*second)
    return mu,Symmetric(inv(first))
end

@time mu,var = get_para(Y,R,t_square,lambda0,W)
#rand(MvNormal(mu,Symmetric(var)))

  1.550833 seconds (3.78 M allocations: 181.023 MiB, 4.38% gc time)


([1.51429, 1.14286, 0.793651], [0.0571429 -0.0 -0.0; -0.0 0.214286 -0.142857; -0.0 -0.142857 0.150794])

In [934]:
mu

3-element Array{Float64,1}:
 1.5142857142857142
 1.1428571428571435
 0.7936507936507936

In [935]:
var

3×3 Symmetric{Float64,Array{Float64,2}}:
  0.0571429  -0.0       -0.0     
 -0.0         0.214286  -0.142857
 -0.0        -0.142857   0.150794

## L = cholesky(var)

In [936]:
res = randn(3)
res = L.U*res + mu
function sampling(mu,var,n)
    res = randn(n)
    L = cholesky(var)
    res = L.L*res + mu
    return res
end
sampling(mu,var,3)

3-element Array{Float64,1}:
 1.3077669864914216 
 1.9542904314155036 
 0.18654086366161748

In [937]:
#Fake data
y1=[1,2,3]
y2=[4,5,6]
Y1=get_my_Y(y1)
Y2=get_my_Y(y2)
Y=[Y1,Y2]
R=[1 0 0;0 2 0; 0 0 3]
w1=[6 7 8]
w2=[6 3 4]
W=[w1 w2]
t_square = 3
lambda0 = 4
number=2


2

In [14]:
Y=[Y1,Y2]

#Y is the data for all individuals
function unlist(Y)
    res = Y[1]
    for i = 2:length(Y)
        res = vcat(res,Y[i])
    end
    return res
end

unlist(Y)

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 2.0  0.0  0.0
 0.0  2.0  3.0
 0.0  0.0  0.0
 5.0  0.0  0.0
 0.0  5.0  6.0

In [939]:
function get_para(Y,R,W,t_square,lambda0,number)
    m = size(Y[1])[1]#number of rows
    n::Int64=(m*(m-1))/2 #number of columns
    Y = unlist(Y) #Set big Y matrix
    
    #Define sparse matrix
    I = collect(1:number*m); J=collect(1:number*m);V = repeat(diag(R),number)
    R = sparse(I,J,V)
    
    #formula calculation
    println(Y)
    first = Y*inv(Matrix(R))*Y' + Diagonal(ones(m,m))
    second = Y*inv(Matrix(R))*transpose(vcat(W)) + ones(m,1)*lambda0*t_square
    mu = vec(inv(first)*second)
    return mu,Symmetric(inv(first))
end



get_para (generic function with 3 methods)

In [607]:
a, b = get_para(Y,R,W,t_square,lambda0,number)

[0.0 0.0 0.0 0.0 0.0 0.0; 2.0 0.0 0.0 5.0 0.0 0.0; 0.0 2.0 3.0 0.0 5.0 6.0]


([12.0, 1.8, 1.39344], [1.0 0.0 0.0; 0.0 0.0333333 0.0; 0.0 0.0 0.0327869])

### Sparse Version

In [78]:
#Y is a data for single persion
y1 = [1,2,3]
function get_sparse_Y(Y)
    m = size(Y)[1] #number of rows
    n::Int64=(m*(m-1))/2  #number of columns
    col_index = collect(1:n)
    row_index = [];value = []
    for i = 2:m
        current = fill(i,i-1) #get a element i with i-1 time
        row_index = vcat(row_index,current)
        current_value = Y[2:i]
        value = vcat(value,current_value)
    end
    
    #Return the sparse matrix
    row_index = convert(Array{Int64,1}, row_index) #change Any type
    value = convert(Array{Float64,1}, value) #Change Any type

    res = sparse(row_index,col_index,value)
end

get_sparse_Y(y1)

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [2, 1]  =  2.0
  [3, 2]  =  2.0
  [3, 3]  =  3.0

In [32]:
#Fake data
y1=[1,2,3]
y2=[4,5,6]
ys1=get_sparse_Y(y1)
ys2=get_sparse_Y(y2)
YS = [ys1,ys2]
R=[1 0 0;0 2 0; 0 0 3]
w1=[6,7,8]
w2=[6,3,4]
W=[w1,w2]
t_square = 3
lambda0 = 4
m = 3
number = 10000

10000

In [107]:
YS = repeat([get_sparse_Y(rand(3))],10000)
YS = unlist(YS)
#W=unlist(W)
W = rand(30000)

function get_sparse_para(YS,R,W,t_square,lambda0,number,m)
    
    #Define residual matrix
    value = diag(R).^(-1)
    RS = kron(sparse(I,number,number),sparse(1:m,1:m,value))
    
    #formula calculation
    YS_RS_product = YS'*RS
    first = YS_RS_product*YS + t_square*sparse(I,m,m)
    second = YS_RS_product*W + ones(m,1)*lambda0*t_square
    
    #Return the result
    first = inv(Matrix(first))
    mu = vec(first*second)
    var = Symmetric(first)
    
    #Take sample
    res = rand(MvNormal(mu,var))
    return res
end

get_sparse_para (generic function with 1 method)

In [145]:
#a,b = get_sparse_para(YS,R,W,t_square,lambda0,number,3)#
@time lambda= get_sparse_para(YS,R,W,t_square,lambda0,number,m)

  0.012986 seconds (94 allocations: 2.629 MiB)


3-element Array{Float64,1}:
  1.2709140524381115
  1.7635319853504563
 -0.3088028298227296

In [165]:
y1 = rand(1000);y2 = rand(1000);y3=rand(1000)
BigY = [y1;y2;y3]
Lambda = [1 0 0; lambda[1] 1 0;lambda[2] lambda[3] 1]

function Modify_Y(Lambda,Y,n_individuals)
    Identy = Matrix{Int32}(I,n_individuals,n_individuals)
    res = kron(Identy,Lambda)*BigY
    return res
end

Modify_Y(Lambda,BigY,1000)

3000-element Array{Float64,1}:
 0.835868553906149  
 1.4672655496887028 
 2.0196146513443582 
 0.30662054586120413
 0.8255494851269182 
 0.7600117337038127 
 0.7306152278398694 
 1.227650623126818  
 1.3104486633455836 
 0.7853803142581395 
 1.6089873339049947 
 1.2086772251104698 
 0.6427183055248529 
 ⋮                  
 0.0735243120054323 
 0.962064479969067  
 0.28077094662393476
 0.06597310768248232
 1.0674494850176846 
 0.6178924178645187 
 0.9222932547213181 
 1.716291708549789  
 2.0017038125907805 
 0.04290698232639212
 0.9480323721573559 
 0.5303543113556766 